apiVersion: v1
kind: Service
metadata:
  name: webdisplay
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    name: webdisplay
  selector:
    k8s-app: webdisplay